"""
DiseaseRiskAgent data models.

Every major flood is followed by a disease outbreak. This is not
unpredictable — cholera has a 2–5 day incubation, typhoid 6–30 days,
leptospirosis 2–30 days. DiseaseRiskAgent operates in the incubation
window: if medical supplies reach a neighborhood BEFORE symptoms
appear, an outbreak is preventable.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from floodops.models.enums import Pathogen
from floodops.models.geo import BBox, GeoJsonFeatureCollection


class PathogenRisk(BaseModel):
    """Risk score for a single pathogen in a single cell."""

    pathogen: Pathogen
    risk_score: float = Field(..., ge=0.0, le=1.0)
    peak_date: datetime | None = None
    incubation_days_min: int = Field(..., ge=0)
    incubation_days_max: int = Field(..., ge=0)
    intervention_window_hours: float = Field(
        ..., ge=0,
        description="Hours remaining before symptom onset makes prevention ineffective"
    )


class DiseaseRiskMap(BaseModel):
    """Spatial disease risk map at 100m grid resolution.

    Each cell has risk scores for cholera, typhoid, and leptospirosis
    across three time windows (0–7d, 7–14d, 14–30d post-flood).
    """

    map_id: str
    event_id: str
    bbox: BBox
    cells: GeoJsonFeatureCollection = Field(
        ...,
        description="Each Feature has properties: { cholera_risk, typhoid_risk, "
                    "lepto_risk, time_window, population_exposed }"
    )
    time_window: str = Field(..., description="0-7d / 7-14d / 14-30d post-flood")
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class Hotspot(BaseModel):
    """A high-risk area where pathogen risk > 0.7."""

    zone_id: str
    pathogen: Pathogen
    risk_score: float = Field(..., ge=0.7, le=1.0)
    peak_date: datetime
    population_exposed: int = Field(..., ge=0)
    lat: float
    lng: float


class MedicalSupplyOrder(BaseModel):
    """Supply order generated by DiseaseRiskAgent for ResourceAgent."""

    zone_id: str
    ors_sachets: int = Field(0, ge=0, description="Oral Rehydration Salts — cholera primary treatment")
    antibiotic_courses: int = Field(0, ge=0, description="Doxycycline (cholera prophylaxis), Azithromycin (typhoid)")
    water_purification_tabs: int = Field(0, ge=0)
    delivery_deadline: datetime = Field(..., description="Must arrive before symptom onset")
    priority: int = Field(1, ge=1)


class DiseaseRiskReport(BaseModel):
    """Complete DiseaseRiskAgent output."""

    report_id: str
    event_id: str
    bbox: BBox
    risk_maps: list[DiseaseRiskMap] = Field(default_factory=list, description="One per time window")
    hotspots: list[Hotspot] = Field(default_factory=list)
    supply_orders: list[MedicalSupplyOrder] = Field(default_factory=list)
    outbreak_risk_cleared: bool = Field(False, description="Gate condition: all risks below threshold")
    generated_at: datetime = Field(default_factory=datetime.utcnow)
