"""
GLOFAgent data models.

GLOFAgent monitors glacial lakes for outburst flood risk. It tracks lake
volume changes via SAR imagery and scores dam (moraine/ice) integrity.

CRITICAL: Confirmed GLOF breaches (integrity < 0.3) route DIRECTLY to
AlertAgent via HTTP, bypassing all queues — seconds matter when a moraine
dam fails. This bypass is the key architectural difference from all other
agent communication.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from floodops.models.geo import BBox, Coordinate, GeoJsonGeometry


class VolumeEstimate(BaseModel):
    """Lake volume estimate derived from SAR surface area + depth model."""

    lake_id: str
    surface_area_km2: float = Field(..., ge=0)
    estimated_depth_m: float = Field(..., ge=0)
    current_volume_m3: float = Field(..., ge=0)
    previous_volume_m3: float = Field(..., ge=0, description="Volume at last measurement")
    volume_delta_m3: float = Field(..., description="Change since last measurement (positive = filling)")
    volume_delta_pct: float = Field(..., description="Percentage change")
    measurement_date: datetime
    source: Literal["SAR", "optical", "altimetry"] = "SAR"


class LakeHealthReport(BaseModel):
    """Comprehensive health assessment for a single glacial lake.

    Produced on every 6-day scan cycle. The integrity_score [0–1] is
    the most critical field — values below 0.3 trigger emergency bypass.
    """

    lake_id: str
    lake_name: str | None = None
    location: Coordinate
    bbox: BBox
    elevation_m: float = Field(..., description="Lake surface elevation")
    dam_type: Literal["moraine", "ice", "bedrock", "unknown"] = "unknown"

    # Volume tracking
    volume: VolumeEstimate

    # Dam integrity — THE critical metric
    integrity_score: float = Field(
        ..., ge=0.0, le=1.0,
        description="Dam structural integrity: 0=failed, 1=stable. "
                    "Moraine: DEM differencing detects erosion. "
                    "Ice: SAR coherence detects thinning. "
                    "< 0.3 triggers DIRECT AlertAgent bypass."
    )

    risk_level: str = Field(..., description="LOW / MEDIUM / HIGH / CRITICAL")
    scan_date: datetime
    next_scan_date: datetime | None = None

    # LLM interpretation
    assessment: str | None = Field(
        None,
        description="LLM-generated assessment explaining why this "
                    "integrity score was assigned and what to watch for."
    )


class ImpactZone(BaseModel):
    """Predicted downstream impact if a glacial lake breaches.

    Generated by routing lake volume through the downstream DEM.
    This is sent with GLOF emergency alerts so responders know
    exactly which areas and when.
    """

    lake_id: str
    geometry: GeoJsonGeometry = Field(..., description="GeoJSON polygon of predicted inundation area")
    peak_discharge_m3s: float = Field(..., ge=0, description="Estimated peak outflow in m³/s")
    time_to_impact_minutes: float = Field(
        ..., ge=0,
        description="Minutes until flood front reaches first populated area. "
                    "This is why GLOF bypasses queues — this number can be < 30."
    )
    affected_population: int = Field(0, ge=0, description="Estimated people in impact zone")
    flood_depth_max_m: float = Field(..., ge=0, description="Max predicted depth in impact zone")
    confidence: float = Field(..., ge=0.0, le=1.0)
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class GLOFEmergency(BaseModel):
    """Direct HTTP bypass payload for confirmed GLOF breach.

    Sent synchronously from GLOFAgent → AlertAgent.
    NO QUEUE. NO DELAY. This is the time-critical path.
    """

    lake_id: str
    lake_name: str | None = None
    integrity_score: float = Field(..., ge=0.0, le=1.0)
    impact_zone: ImpactZone
    breach_type: Literal["confirmed", "imminent"] = "imminent"
    recommended_action: str = "IMMEDIATE_EVACUATION"
    timestamp: datetime = Field(default_factory=datetime.utcnow)
